### ISSUE TITLE
EPIC: Add support for provisioning Oracle Cloud resources and installing TAP

### ISSUE THREAD

**Issue by pacphi** [pacphi/gha-workflows-with-gitops-for-tanzu-application-platform#3]
This is a significant effort which would at a minimum include:

* [x] Research and validation of an updated approach supporting TAP 1.3 and beyond
* [x] Implementation of Packer module for custom toolset image
* [x] Implementation of Terraform modules (IAM, Compartment, DNS Zones, VCN, Clusters, Registry)
* [ ] Additional implementation of Terraform modules (Bastion, [backend support](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformUsingObjectStore.htm), Secrets Manager, Secrets Manager Secrets)
* [x] Impl of Gitops modules
* [ ] Design and implementation of custom Docker images for use by Github Action workflows (would package oci CLI along with other required CLIs)
* [ ] Implementation of Github Actions (dispatch and call workflows)
* [ ] Update observe-clusters.sh and gh-set-secrets.sh
* [x] Authoring ORACLE.md
* [ ] Authoring sample workflows based on use of Github CLI
* [x] Updating README.md

The good news is there was an earlier effort conducted targeting TAP 1.0. See instructions and imperative workflow found [here](https://github.com/pacphi/make-onboarding-suck-less/tree/main/scripts/tanzu/application-platform/oci).
